### ISSUE TITLE
[Meta] Merge upstream Secret Store

### ISSUE THREAD

**Issue by svyatonik** [paritytech/secret-store#4]
The idea is to have SS implementation that'll work for different blockchains (we will have impl for Ethereum-like and Substrate-based chains). The has been done in the [separate repo](https://github.com/svyatonik/secret-store) and is still WIP, but since we now have a 1.0 commit here. I'd like to start moving all the work here.

The merging strategy would be a bit uncommon, since first I want to introduce code that won't be used by any other code in this repository. But it would be easier (I believe both for me and reviewers) to start that way and then update `key-server` in one big (or several lesser) PRs.

Some words on new repo structure. We need `primitives` crate that will be used to communicate with `KeyServer` implementation. The `key-server` crate will expose implementation of `KeyServer` trait (and some others). There won't be any builtin services (service is an endpoint that is accepting external requests and publishing responses) in `key-server` crate. Instead, there'll be separate service (library) crates: `http-service` to serve HTTP requests, `blockchain-service` (and descendants - `substrate-service` and `ethereum-service`) for serving requests that come from the blockchain. Additionaly, there'll be several binaries, but the set is not final yet.

There's also 'contract' part of the SS - solidity contracts for Ethereum-like chains and runtime module for Substrate-based chains. The latter (I believe) will also be moved here. I'm not sure now about contracts.

The `key-server` crate is also a bit reorganized - i.e. I have extracted transport part into separate folder, as well as rocksdb-based key storage (at least I'm going to). This reorg mostly affects code that is exposed from the crate. But the final reorg and fixes will be done a bit later (when upstream code will be merged).

- [ ] Prepare and merge upstream primitives crate
- [ ] Prepare and merge upstream http-service crate
- [ ] Prepare and merge upstream blockchain-service crate
- [ ] Prepare and merge upstream ethereum-service crate
- [ ] Prepare and merge upstream substrate-service crate
- [ ] Prepare and merge substrate runtime module crate (should be done after Substrate release)
- [ ] Select, prepare and merge binaries

**Comment by svyatonik** [comment]
After some thoughts, I'm believing now that the repo could benefit from having a substrate node that runs runtime with SecretStore module. Having it, is the best way to introduce ss-for-substrate binary and corresponding integration tests.
